// Generated by Dagger (https://dagger.dev).
package com.example.notesapp.presentation.viewmodel;

import com.example.notesapp.domain.repository.NotesDataManager;

import dagger.internal.Factory;

import javax.inject.Provider;

@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class NotesListVM_Factory implements Factory<NotesListVM> {
    private final Provider<NotesDataManager> dataManagerProvider;

    public NotesListVM_Factory(Provider<NotesDataManager> dataManagerProvider) {
        this.dataManagerProvider = dataManagerProvider;
    }

    @Override
    public NotesListVM get() {
        return newInstance(dataManagerProvider.get());
    }

    public static NotesListVM_Factory create(Provider<NotesDataManager> dataManagerProvider) {
        return new NotesListVM_Factory(dataManagerProvider);
    }

    public static NotesListVM newInstance(NotesDataManager dataManager) {
        return new NotesListVM(dataManager);
    }
}
