// Generated by Dagger (https://dagger.dev).
package com.example.notesapp.presentation.viewmodel;

import com.example.notesapp.model.NotesDataManager;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class NoteDetailVM_Factory implements Factory<NoteDetailVM> {
  private final Provider<NotesDataManager> dataManagerProvider;

  public NoteDetailVM_Factory(Provider<NotesDataManager> dataManagerProvider) {
    this.dataManagerProvider = dataManagerProvider;
  }

  @Override
  public NoteDetailVM get() {
    return newInstance(dataManagerProvider.get());
  }

  public static NoteDetailVM_Factory create(Provider<NotesDataManager> dataManagerProvider) {
    return new NoteDetailVM_Factory(dataManagerProvider);
  }

  public static NoteDetailVM newInstance(NotesDataManager dataManager) {
    return new NoteDetailVM(dataManager);
  }
}
